---
{{- if .Values.ssm.schedule }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: notebooks-accounting-ssm-config
  labels:
    {{- include "notebooks-accounting.labels" . | nindent 4 }}
data:
  sender.cfg: |-
    [sender]
    # Either 'STOMP' for STOMP message brokers or 'AMS' for Argo Messaging Service
    protocol: AMS
    ################################################################################
    # Required: broker configuration options
    #
    [broker]
    # The SSM will query a BDII to find brokers available.  These details are for the
    # EGI production broker network
    # bdii: ldap://lcg-bdii.cern.ch:2170
    # network: PROD
    # Alternatively, 'host' and 'port' may be set manually (with 'bdii' and
    # 'network' commented out). This option must be used for AMS.
    #host: msg-devel.argo.grnet.gr
    host: {{ .Values.ssm.broker.host }}
{{- if .Values.ssm.broker.port }}
    port: {{ .Values.ssm.broker.port }}
{{- end }}
    # broker authentication.  If use_ssl is set, the certificates configured
    # in the mandatory [certificates] section will be used.
    use_ssl: false
    ################################################################################
    # Required: Certificate configuration
    [certificates]
    certificate: /etc/grid-security/hostcert.pem
    key: /etc/grid-security/hostkey.pem
    capath: /etc/grid-security/certificates
    # If this is supplied, outgoing messages will be encrypted
    # using this certificate
    #server_cert: /etc/grid-security/servercert.pem
    ################################################################################
    # Messaging configuration.
    #
    [messaging]
    # If using AMS this is the project that SSM will connect to. Ignored for STOMP.
    ams_project: accounting
    # Queue to which SSM will send messages
    destination: {{ .Values.ssm.messaging.destination }}
    # Supplied path type ('dirq', 'directory')
    # path_type: dirq
    # Outgoing messages will be read and removed from this directory.
    path: {{ .Values.ssm.messaging.path | default "/accounting/ssm" }}
{{- if .Values.ssm.messaging.token }}
    token: {{ .Values.ssm.messaging.token }}
{{- end }}
    [logging]
    logfile: /var/log/apel/ssmsend.log
    # Available logging levels:
    # DEBUG, INFO, WARN, ERROR, CRITICAL
    level: DEBUG
    console: true
{{- end }}
